baseURL = "http://kwbode.uber.space/"
title = "Konstantin Bode"
theme = "bode"
enableEmoji = true

defaultContentLanguage = "en"

[languages]
    [languages.en]
    weight=1
    [languages.de]
    weight=2
